cache: yarn
language: node_js
node_js:
  - "8"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version version-number
  - export PATH="$HOME/.yarn/bin:$PATH
script:
  - git clone https://github.com/swaponline/swap.core
  - npm install
  - npm run build
  
