name: Pullrequest build & test

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.20.0]

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Decrypt testWallets.json.gpg file
      if: ${{ env.SECRET_PASSPHRASE != '' }}
      shell: bash
      env:
        SECRET_PASSPHRASE: ${{ secrets.SECRET_PASSPHRASE_FOR_TESTS }}
      run: >
        ./.github/scripts/decrypt_secret.sh
    - name: npm install
      uses: bahmutov/npm-install@v1
      with:
       useLockFile: false
    - name: build mainnet
      run: |
        npm run clean:mainnet
        cross-env NODE_ENV=production DEBUG=app:* CONFIG=mainnet.prod node --max-old-space-size=5120 ./src/front/bin/compile
    - name: build mainnet widget
      run: |
        npm run build:mainnet-widget
    - name: build testnet for tests
      run: |
        npm run build:testnet-tests
    # - name: run e2e tests
      # run: |
        # mkdir ./tests/e2e/screenshots
        # npm run test:e2e:actions
    # - name: Upload failure screenshots
      # uses: actions/upload-artifact@v4
      # if: failure()
      # with:
        # name: failure-screenshots
        # path: ./tests/e2e/screenshots
        # if-no-files-found: ignore
    # - name: Upload screenshots
      # uses: actions/upload-artifact@v4
      # with:
        # name: screenshots
        # path: ./tests/e2e/screenshots
        # if-no-files-found: ignore
      # env:
        # CI: true
